kind: Deployment
apiVersion: apps/v1
metadata:
  name: datahug-webapp-dev
  namespace: default
  labels:
    app: datahug-webapp-dev
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahug-webapp-dev
  template:
    metadata:
      labels:
        app: datahug-webapp-dev
        role: rolling-update
        build_number: '<TAG>'
    spec:
      containers:
        - name: datahug-webapp-dev
          image: 'bakcovn/datahug-webapp-dev:latest'
      imagePullSecrets:
        - name: regcred
  strategy:
    type: RollingUpdate
